// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.js");
var Route$ReactTemplate = require("./Route.js");
var Words$ReactTemplate = require("./Words.js");
var HomePage$ReactTemplate = require("./HomePage.js");
var AboutPage$ReactTemplate = require("./AboutPage.js");
var StatsPage$ReactTemplate = require("./StatsPage.js");
var MarketPage$ReactTemplate = require("./MarketPage.js");
var TreasuryPage$ReactTemplate = require("./TreasuryPage.js");
var GovernancePage$ReactTemplate = require("./GovernancePage.js");

var component = ReasonReact.statelessComponent("SiteNavLink");

function make(route, label, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(route, /* Some */["site-nav__link"], /* array */[Words$ReactTemplate.translate(/* English */0, label)]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var SiteNavLink = /* module */[
  /* component */component,
  /* make */make
];

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

var component$1 = ReasonReact.reducerComponent("App");

function make$1() {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */(function () {
              document.addEventListener("scatterLoaded", (function () {
                      console.log("scatter loaded");
                      return /* () */0;
                    }));
              return /* () */0;
            }),
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var tmp;
              switch (match) {
                case 0 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, HomePage$ReactTemplate.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, MarketPage$ReactTemplate.make(/* array */[]));
                    break;
                case 2 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, TreasuryPage$ReactTemplate.make(/* array */[]));
                    break;
                case 3 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, GovernancePage$ReactTemplate.make(/* array */[]));
                    break;
                case 4 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, StatsPage$ReactTemplate.make(/* array */[]));
                    break;
                case 5 : 
                    tmp = ReasonReact.element(/* None */0, /* None */0, AboutPage$ReactTemplate.make(/* array */[]));
                    break;
                
              }
              return React.createElement("div", {
                          className: "site-container"
                        }, React.createElement("header", {
                              className: "site-header"
                            }, ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make(/* Home */0, /* Some */["site-logo"], /* array */["TGFP"])), React.createElement("nav", {
                                  className: "site-nav"
                                }, ReasonReact.element(/* None */0, /* None */0, make(/* Market */1, /* Market */0, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(/* Treasury */2, /* Treasury */2, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(/* Governance */3, /* Games */1, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(/* Governance */3, /* Governance */3, /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(/* Stats */4, /* Stats */4, /* array */[]))), React.createElement("nav", {
                                  className: "user-nav"
                                }, React.createElement("a", {
                                      className: "user-nav__login-link",
                                      href: "#"
                                    }, "Login"))), React.createElement("main", {
                              className: "page-container"
                            }, tmp));
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[Route$ReactTemplate.fromUrl(url)]);
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

exports.SiteNavLink = SiteNavLink;
exports.reducer = reducer;
exports.component = component$1;
exports.make = make$1;
/* component Not a pure module */
