// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Algolia$ReactTemplate = require("./Algolia.js");

var component = ReasonReact.statelessComponent("MarketPage");

function hitComponent(hitResult) {
  var hit = hitResult.hit;
  console.log(hit);
  return React.createElement("div", {
              className: "hit"
            }, React.createElement("h3", undefined, ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.Highlight[/* make */0]("name", hit, /* array */[]))));
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "market-page"
                        }, React.createElement("aside", {
                              className: "market-page__filters"
                            }, React.createElement("h2", undefined, "Filters")), React.createElement("main", {
                              className: "market-page__results"
                            }, ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.InstantSearch[/* make */0]("neato", "5085ce346201999ee5e28e32380ceab1", "X0210UMLR1", "dev_market", /* array */[
                                      ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.Breadcrumb[/* make */0](/* array */[
                                                "category.lvl0",
                                                "category.lvl1"
                                              ], /* array */[])),
                                      ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.HierarchicalMenu[/* make */0](/* array */[
                                                "category.lvl0",
                                                "category.lvl1"
                                              ], /* array */[])),
                                      ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.SearchBox[/* make */0](/* None */0, /* array */[])),
                                      ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.Stats[/* make */0](/* array */[])),
                                      ReasonReact.element(/* None */0, /* None */0, Algolia$ReactTemplate.Hits[/* make */0](hitComponent, /* array */[]))
                                    ]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.hitComponent = hitComponent;
exports.make = make;
/* component Not a pure module */
